/*
    --관리자 계정에서 MASTER 계정 생성, 권한 부여
    CREATE USER MASTER IDENTIFIED BY MASTER;
    GRANT CONNECT, RESOURCE TO MASTER;    
*/

--------------------------------------------------
----------------  MEMBER 관련	 -----------------
--------------------------------------------------

DROP TABLE MEMBER; --멤버 테이블 제거
DROP TABLE PRODUCT; --상품 테이블 제거
DROP TABLE CATEGORY; --카테고리 테이블 제거
DROP TABLE MASTER; --장인 테이블 제거

DROP SEQUENCE SEQ_MNO; --회원번호 시퀀스 제거
DROP SEQUENCE SEQ_PNO; --상품번호 시퀀스 제거
DROP SEQUENCE SEQ_MSTNO; --장인번호 시퀀스 제거

CREATE TABLE MEMBER ( --멤버 테이블 생성
    MEM_NO  NUMBER PRIMARY KEY,
	MEM_ID	VARCHAR2(30) NOT NULL UNIQUE,
    MEM_PW	VARCHAR2(100) NOT NULL,
	MEM_NAME	VARCHAR2(15) NOT NULL,
	MEM_PHONE	VARCHAR2(15) NOT NULL,
    MEM_EMAIL	VARCHAR2(100) NOT NULL,
	MEM_ADDRESS	VARCHAR2(120) NOT NULL,
	GRADE VARCHAR2(10) DEFAULT '일반' CHECK (GRADE IN('일반','장인','관리자')),
	ENROLLDATE	DATE DEFAULT SYSDATE,
	ENROLLFLAG	VARCHAR2(1) DEFAULT 'Y' CHECK (ENROLLFLAG IN('Y', 'N')),
	DELETEDATE	DATE DEFAULT NULL
);

COMMENT ON COLUMN MEMBER.MEM_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.MEM_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.MEM_PW IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.MEM_PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.MEM_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.MEM_ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.GRADE IS '등급';
COMMENT ON COLUMN MEMBER.ENROLLDATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.ENROLLFLAG IS '회원등록여부(Y/N)';
COMMENT ON COLUMN MEMBER.DELETEDATE IS '회원탈퇴일';

CREATE SEQUENCE SEQ_MNO
NOCACHE;

INSERT INTO MEMBER --관리자 샘플
VALUES (SEQ_MNO.NEXTVAL,'admin', '1234', '관리자', '010-1111-2222', 'admin@kh.or.kr', '서울시 강남구 역삼동', '관리자', SYSDATE, DEFAULT, DEFAULT);

INSERT INTO MEMBER --장인 샘플
VALUES (SEQ_MNO.NEXTVAL,'user1', 'pass1', '김장인', '010-3333-4444', 'user01@kh.or.kr', '서울시 양천구 목동', '장인', SYSDATE, DEFAULT, DEFAULT);

INSERT INTO MEMBER --일반 샘플
VALUES (SEQ_MNO.NEXTVAL,'user2', 'pass2', '최일반', '010-7444-1234', 'user02@kh.or.kr', '서울시 강서구', DEFAULT, SYSDATE, DEFAULT, DEFAULT);

--------------------------------------------------
----------------  PRODUCT 관련	 -----------------
--------------------------------------------------

CREATE TABLE PRODUCT (--상품 테이블 생성
	P_NO	NUMBER	PRIMARY KEY,
	CATEGORY_CODE	VARCHAR2(30) NOT NULL,
	MST_NO	NUMBER	NOT NULL,
	P_NAME	VARCHAR2(50) NOT NULL,
	P_PRICE	NUMBER	NOT NULL,
	P_CATEGORY	VARCHAR2(30) NOT NULL,
	P_DESCRIPTION	VARCHAR2(500) NULL,
	P_DATE	DATE DEFAULT SYSDATE,
	P_STOCK	NUMBER	NOT NULL,
	P_HITS	NUMBER	NOT NULL,
	P_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (P_STATUS IN('Y', 'N')),
    FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORY(CATEGORY_CODE),
    FOREIGN KEY (MST_NO) REFERENCES MASTER(MST_NO)
);

CREATE SEQUENCE SEQ_PNO
NOCACHE;

--------------------------------------------------
----------------  CATEGORY 관련	 -----------------
--------------------------------------------------

CREATE TABLE "CATEGORY" (
	"CATEGORY_CODE"	VARCHAR2(30) PRIMARY KEY,
	"CATEGORY_NAME"	VARCHAR2(50) NOT NULL
);



--------------------------------------------------
----------------  MASTER 관련	 -----------------
--------------------------------------------------

CREATE TABLE "MASTER" (
	"MST_NO" NUMBER PRIMARY KEY,
	"MEM_NO" NUMBER,
	"MST_CATEGORY" VARCHAR2(255) NOT NULL,
	"MST_NUMBER" VARCHAR2(255) NOT NULL,
	"STR_NAME" VARCHAR2(255) NOT NULL,
	"MST_STATUS" VARCHAR2(1) DEFAULT 'Y' CHECK (MST_STATUS IN('Y', 'N')),
    FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO)
);

CREATE SEQUENCE SEQ_MSTNO
NOCACHE;



