/*
    --관리자 계정에서 MASTER 계정 생성, 권한 부여
    CREATE USER MASTER IDENTIFIED BY MASTER;
    GRANT CONNECT, RESOURCE TO MASTER;    
*/

DROP TABLE ATTACHMENT; --첨부파일 테이블 제거
DROP TABLE COUPON; --쿠폰 테이블 제거
DROP TABLE HOPE; --찜하기 테이블 제거
DROP TABLE DELIVERY; --송장 테이블 제거
DROP TABLE REFUND; --환불 테이블 제거
DROP TABLE ORDERDETAIL; --주문상세 테이블 제거
DROP TABLE MEMORDER; --주문 테이블 제거
DROP TABLE PAYMENT; --결제 테이블 제거
DROP TABLE NOTICE; --공지 테이블 제거
DROP TABLE BOARD; --게시판 테이블 제거
DROP TABLE PRODUCTQnA; --상품 QnA 테이블 제거
DROP TABLE PRODUCT; --상품 테이블 제거
DROP TABLE CATEGORY; --카테고리 테이블 제거
DROP TABLE MASTER; --장인 테이블 제거
DROP TABLE MEMBER; --멤버 테이블 제거

DROP SEQUENCE SEQ_MNO; --회원번호 시퀀스 제거
DROP SEQUENCE SEQ_MSTNO; --장인번호 시퀀스 제거
DROP SEQUENCE SEQ_PNO; --상품번호 시퀀스 제거
DROP SEQUENCE SEQ_PQNO; --상품QnA번호 시퀀스 제거
DROP SEQUENCE SEQ_BOARDNO; --게시판번호 시퀀스 제거
DROP SEQUENCE SEQ_NOTICENO; --공지번호 시퀀스 제거
DROP SEQUENCE SEQ_PAYNO; --결제번호 시퀀스 제거
DROP SEQUENCE SEQ_ORDERNO; --주문번호 시퀀스 제거
DROP SEQUENCE SEQ_ODNO; --주문상세번호 시퀀스 제거
DROP SEQUENCE SEQ_REFUNDNO; --환불번호 시퀀스 제거
DROP SEQUENCE SEQ_CPNO; --쿠폰번호 시퀀스 제거
DROP SEQUENCE SEQ_FILENO; --첨부파일번호 시퀀스 제거
DROP SEQUENCE SEQ_DVNO; --송장번호 시퀀스 제거

--------------------------------------------------
----------------  MEMBER 관련	 -----------------
--------------------------------------------------
CREATE TABLE MEMBER ( --멤버 테이블 생성
    MEM_NO  NUMBER PRIMARY KEY,
	MEM_ID	VARCHAR2(30) NOT NULL UNIQUE,
    MEM_PW	VARCHAR2(100) NOT NULL,
	MEM_NAME	VARCHAR2(15) NOT NULL,
	MEM_PHONE	VARCHAR2(15) NOT NULL,
    MEM_EMAIL	VARCHAR2(100) NOT NULL,
	MEM_ADDRESS	VARCHAR2(120) NOT NULL,
	GRADE VARCHAR2(10) DEFAULT '일반' CHECK (GRADE IN('일반','장인','관리자')),
	ENROLLDATE	DATE DEFAULT SYSDATE,
	ENROLLFLAG	VARCHAR2(1) DEFAULT 'Y' CHECK (ENROLLFLAG IN('Y', 'N')),
	DELETEDATE	DATE DEFAULT NULL
);
COMMENT ON COLUMN MEMBER.MEM_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.MEM_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.MEM_PW IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.MEM_PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.MEM_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.MEM_ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.GRADE IS '등급';
COMMENT ON COLUMN MEMBER.ENROLLDATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.ENROLLFLAG IS '회원등록여부(Y/N)';
COMMENT ON COLUMN MEMBER.DELETEDATE IS '회원탈퇴일';

CREATE SEQUENCE SEQ_MNO
NOCACHE;

INSERT INTO MEMBER --관리자 샘플
VALUES (SEQ_MNO.NEXTVAL,'admin', '1234', '관리자', '010-1111-2222', 'admin@kh.or.kr', '서울시 강남구 역삼동', '관리자', SYSDATE, DEFAULT, DEFAULT);

INSERT INTO MEMBER --장인 샘플
VALUES (SEQ_MNO.NEXTVAL,'user1', 'pass1', '김장인', '010-3333-4444', 'user01@kh.or.kr', '서울시 양천구 목동', '장인', SYSDATE, DEFAULT, DEFAULT);

INSERT INTO MEMBER --일반 샘플
VALUES (SEQ_MNO.NEXTVAL,'user2', 'pass2', '최일반', '010-7444-1234', 'user02@kh.or.kr', '서울시 강서구', DEFAULT, SYSDATE, DEFAULT, DEFAULT);

--------------------------------------------------
----------------  CATEGORY 관련	 -----------------
--------------------------------------------------
CREATE TABLE "CATEGORY" (
	"CATEGORY_CODE"	VARCHAR2(30) PRIMARY KEY,
	"CATEGORY_NAME"	VARCHAR2(50) NOT NULL
);
COMMENT ON COLUMN CATEGORY.CATEGORY_CODE IS '카테고리코드';
COMMENT ON COLUMN CATEGORY.CATEGORY_NAME IS '카테고리이름';

--------------------------------------------------
----------------  MASTER 관련	 -----------------
--------------------------------------------------
CREATE TABLE "MASTER" (
	"MST_NO" NUMBER PRIMARY KEY,
	"MEM_NO" NUMBER,
	"MST_CATEGORY" VARCHAR2(255) NOT NULL,
	"MST_NUMBER" VARCHAR2(255) NOT NULL,
	"STR_NAME" VARCHAR2(255) NOT NULL,
	"MST_STATUS" VARCHAR2(1) DEFAULT 'Y' CHECK (MST_STATUS IN('Y', 'N')),
    FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO)
);
COMMENT ON COLUMN MASTER.MST_NO IS '장인번호';
COMMENT ON COLUMN MASTER.MEM_NO IS '회원번호';
COMMENT ON COLUMN MASTER.MST_CATEGORY IS '장인카테고리';
COMMENT ON COLUMN MASTER.MST_NUMBER IS '사업자등록번호';
COMMENT ON COLUMN MASTER.STR_NAME IS '상점명';
COMMENT ON COLUMN MASTER.MST_STATUS IS '상태';

CREATE SEQUENCE SEQ_MSTNO
NOCACHE;


--------------------------------------------------
----------------  PRODUCT 관련	 -----------------
--------------------------------------------------
CREATE TABLE PRODUCT (--상품 테이블 생성
	P_NO	NUMBER	PRIMARY KEY,
	CATEGORY_CODE	VARCHAR2(30) NOT NULL,
	MST_NO	NUMBER	NOT NULL,
	P_NAME	VARCHAR2(50) NOT NULL,
	P_PRICE	NUMBER	NOT NULL,
	P_CATEGORY	VARCHAR2(30) NOT NULL,
	P_DESCRIPTION	VARCHAR2(500) NULL,
	P_DATE	DATE DEFAULT SYSDATE,
	P_STOCK	NUMBER	NOT NULL,
	P_HITS	NUMBER	NOT NULL,
	P_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (P_STATUS IN('Y', 'N')),
    FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORY(CATEGORY_CODE),
    FOREIGN KEY (MST_NO) REFERENCES MASTER(MST_NO)
);
COMMENT ON COLUMN PRODUCT.P_NO IS '상품번호';
COMMENT ON COLUMN PRODUCT.CATEGORY_CODE IS '카테고리코드';
COMMENT ON COLUMN PRODUCT.P_NAME IS '상품이름';
COMMENT ON COLUMN PRODUCT.P_PRICE IS '상품가격';
COMMENT ON COLUMN PRODUCT.P_CATEGORY IS '상품종류';
COMMENT ON COLUMN PRODUCT.P_DESCRIPTION IS '상품설명';
COMMENT ON COLUMN PRODUCT.P_DATE IS '등록일';
COMMENT ON COLUMN PRODUCT.P_STOCK IS '상품재고';
COMMENT ON COLUMN PRODUCT.P_HITS IS '조회수';
COMMENT ON COLUMN PRODUCT.P_STATUS IS '상품상태';

CREATE SEQUENCE SEQ_PNO
NOCACHE;

--------------------------------------------------
-------------  PRODUCT QnA 관련	 -----------------
--------------------------------------------------
CREATE TABLE PRODUCTQnA (--상품 QnA 테이블 생성
    PQ_NO NUMBER PRIMARY KEY,
	P_NO NUMBER NOT NULL,
	MEM_NO	NUMBER NOT NULL,
	PQ_TITLE	VARCHAR2(50) NOT NULL,
	PQ_PWD	NUMBER NULL,
	PQ_CONTENT VARCHAR2(2000)NOT NULL,
	PQ_DATE	DATE DEFAULT SYSDATE,
	PQ_HITS	NUMBER NOT NULL,
	PQ_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (PQ_STATUS IN('Y', 'N')),
    FOREIGN KEY (P_NO) REFERENCES PRODUCT(P_NO),
    FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO)
);
COMMENT ON COLUMN PRODUCTQnA.PQ_NO IS '문의번호';
COMMENT ON COLUMN PRODUCTQnA.P_NO IS '상품번호';
COMMENT ON COLUMN PRODUCTQnA.MEM_NO IS '회원번호';
COMMENT ON COLUMN PRODUCTQnA.PQ_TITLE IS '문의제목';
COMMENT ON COLUMN PRODUCTQnA.PQ_PWD IS '비밀글비밀번호';
COMMENT ON COLUMN PRODUCTQnA.PQ_CONTENT IS '문의내용';
COMMENT ON COLUMN PRODUCTQnA.PQ_DATE IS '작성날짜';
COMMENT ON COLUMN PRODUCTQnA.PQ_HITS IS '조회수';
COMMENT ON COLUMN PRODUCTQnA.PQ_STATUS IS '게시글상태';

CREATE SEQUENCE SEQ_PQNO
NOCACHE;

--------------------------------------------------
-----------------  BOARD 관련	 -----------------
--------------------------------------------------
CREATE TABLE BOARD (
	BOARD_NO NUMBER PRIMARY KEY,
	P_NO	NUMBER NOT NULL,
	MEM_NO	NUMBER NOT NULL,
    BOARD_TITLE VARCHAR2(50) NOT NULL,
	BOARD_CONTENT	VARCHAR2(2000) NOT NULL,
	BOARD_DATE	DATE DEFAULT SYSDATE,
	STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    FOREIGN KEY (P_NO) REFERENCES PRODUCT(P_NO),
    FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO)
);
COMMENT ON COLUMN BOARD.BOARD_NO IS '게시판글번호';
COMMENT ON COLUMN BOARD.P_NO IS '상품번호';
COMMENT ON COLUMN BOARD.MEM_NO IS '회원번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '내용';
COMMENT ON COLUMN BOARD.BOARD_DATE IS '작성날짜';
COMMENT ON COLUMN BOARD.STATUS IS '상태';

CREATE SEQUENCE SEQ_BOARDNO
NOCACHE;

--------------------------------------------------
----------------  NOTICE 관련	 -----------------
--------------------------------------------------
CREATE TABLE NOTICE (
	NOTICE_NO	NUMBER	PRIMARY KEY,
	MEM_NO	NUMBER	NOT NULL,
	NOTICE_TITLE	VARCHAR2(50) NOT NULL,
	NOTICE_DATE	DATE DEFAULT SYSDATE,
	NOTICE_HITS	NUMBER NOT NULL,
	NOTICE_CONTENT	VARCHAR2(500)	NULL,
	NOTICE_CATEGORY	VARCHAR2(30)	NULL,
    FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO)
);
COMMENT ON COLUMN NOTICE.NOTICE_NO IS '게시물번호';
COMMENT ON COLUMN NOTICE.MEM_NO IS '회원번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '게시물제목';
COMMENT ON COLUMN NOTICE.NOTICE_DATE IS '등록일';
COMMENT ON COLUMN NOTICE.NOTICE_HITS IS '조회수';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '내용';
COMMENT ON COLUMN NOTICE.NOTICE_CATEGORY IS '카테고리';

CREATE SEQUENCE SEQ_NOTICENO
NOCACHE;

--------------------------------------------------
----------------  PAYMENT 관련	 -----------------
--------------------------------------------------
CREATE TABLE PAYMENT (
	PAY_NO	NUMBER PRIMARY KEY,
	PAY_NAME	VARCHAR2(40) NOT NULL
);
COMMENT ON COLUMN PAYMENT.PAY_NO IS '결제수단번호';
COMMENT ON COLUMN PAYMENT.PAY_NAME IS '결제수단이름';

CREATE SEQUENCE SEQ_PAYNO
NOCACHE;

--------------------------------------------------
-----------------  ORDER 관련	 -----------------
--------------------------------------------------
CREATE TABLE MEMORDER (
	O_NO	NUMBER PRIMARY KEY,
	MEM_NO	NUMBER	NOT NULL,
	PAY_NO	NUMBER	NOT NULL,
	O_ADDRESS	VARCHAR2(200) NOT NULL,
	RECIVER_NAME	VARCHAR2(20) NOT NULL,
	RECIVER_PHONE	VARCHAR2(11) NOT NULL,
	O_DATE	DATE DEFAULT SYSDATE,
	MEM_FLAG VARCHAR2(1) DEFAULT 'Y' CHECK (MEM_FLAG IN('Y', 'N')),
    FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO),
    FOREIGN KEY (PAY_NO) REFERENCES PAYMENT(PAY_NO)
);
COMMENT ON COLUMN MEMORDER.O_NO IS '주문번호';
COMMENT ON COLUMN MEMORDER.MEM_NO IS '회원번호';
COMMENT ON COLUMN MEMORDER.PAY_NO IS '결제수단번호';
COMMENT ON COLUMN MEMORDER.O_ADDRESS IS '배송지주소';
COMMENT ON COLUMN MEMORDER.RECIVER_NAME IS '수령자이름';
COMMENT ON COLUMN MEMORDER.RECIVER_PHONE IS '수령자전화번호';
COMMENT ON COLUMN MEMORDER.O_DATE IS '주문일자';
COMMENT ON COLUMN MEMORDER.MEM_FLAG IS '회원여부';

CREATE SEQUENCE SEQ_ORDERNO
NOCACHE;

--------------------------------------------------
--------------  ORDERDETAIL 관련	 -----------------
--------------------------------------------------
CREATE TABLE ORDERDETAIL (
	O_DETAIL_NO	NUMBER	PRIMARY KEY,
	P_NO	NUMBER	NOT NULL,
	O_NO	NUMBER	NOT NULL,
	P_COUNT	NUMBER	NULL,
	P_PRICE	NUMBER	NULL,
	O_STATUS	VARCHAR2(10)	NULL,
	O_SERVICE	VARCHAR2(20)	NULL,
	E_DATE	DATE DEFAULT SYSDATE,
	MEM_FLAG	VARCHAR2(1) DEFAULT 'Y' CHECK (MEM_FLAG IN('Y', 'N')),
    FOREIGN KEY (P_NO) REFERENCES PRODUCT(P_NO),
    FOREIGN KEY (O_NO) REFERENCES MEMORDER(O_NO)
);
COMMENT ON COLUMN ORDERDETAIL.O_DETAIL_NO IS '주문상세번호';
COMMENT ON COLUMN ORDERDETAIL.P_NO IS '상품번호';
COMMENT ON COLUMN ORDERDETAIL.O_NO IS '주문번호';
COMMENT ON COLUMN ORDERDETAIL.P_COUNT IS '수량';
COMMENT ON COLUMN ORDERDETAIL.P_PRICE IS '가격';
COMMENT ON COLUMN ORDERDETAIL.O_STATUS IS '처리상태';
COMMENT ON COLUMN ORDERDETAIL.O_SERVICE IS '포장서비스';
COMMENT ON COLUMN ORDERDETAIL.E_DATE IS '체험일';
COMMENT ON COLUMN ORDERDETAIL.MEM_FLAG IS '회원여부';

CREATE SEQUENCE SEQ_ODNO
NOCACHE;

--------------------------------------------------
-----------------  REFUND 관련	 -----------------
--------------------------------------------------
CREATE TABLE REFUND (
	REFUND_NO	NUMBER PRIMARY KEY,
	O_DETAIL_NO	NUMBER	NOT NULL,
	REFUND_REASON	VARCHAR2(500)	NULL,
	REF_FLAG	VARCHAR2(1) DEFAULT 'Y' CHECK (REF_FLAG IN('Y', 'N')),
    FOREIGN KEY (O_DETAIL_NO) REFERENCES ORDERDETAIL(O_DETAIL_NO)
);
COMMENT ON COLUMN REFUND.REFUND_NO IS '환불번호';
COMMENT ON COLUMN REFUND.O_DETAIL_NO IS '주문상세번호';
COMMENT ON COLUMN REFUND.REFUND_REASON IS '환불사유';
COMMENT ON COLUMN REFUND.REF_FLAG IS '환불가능여부';

CREATE SEQUENCE SEQ_REFUNDNO
NOCACHE;

--------------------------------------------------
------------------- HOPE 관련	 -----------------
--------------------------------------------------
CREATE TABLE HOPE (
	MEM_NO	NUMBER	NOT NULL UNIQUE,
	P_NO	NUMBER	NOT NULL,
    FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO),
    FOREIGN KEY (P_NO) REFERENCES PRODUCT(P_NO)
);
COMMENT ON COLUMN HOPE.MEM_NO IS '회원번호';
COMMENT ON COLUMN HOPE.P_NO IS '상품번호';

--------------------------------------------------
------------------- COUPON 관련	 -----------------
--------------------------------------------------
CREATE TABLE COUPON (
	CP_NO	NUMBER	PRIMARY KEY,
    MEM_NO	NUMBER	NOT NULL,
	CP_PRICE	NUMBER	NOT NULL,
	CP_STATUS	VARCHAR2(1) DEFAULT 'Y' CHECK (CP_STATUS IN('Y', 'N')),
	CP_EXPIRE	DATE	DEFAULT SYSDATE,
	CP_CONTENT	VARCHAR2(50) NULL,
	CP_DATE	DATE    DEFAULT SYSDATE,
    FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO)
);
COMMENT ON COLUMN COUPON.CP_NO IS '쿠폰번호';
COMMENT ON COLUMN COUPON.MEM_NO IS '회원번호';
COMMENT ON COLUMN COUPON.CP_PRICE IS '쿠폰가격';
COMMENT ON COLUMN COUPON.CP_STATUS IS '상태';
COMMENT ON COLUMN COUPON.CP_EXPIRE IS '유효기간';
COMMENT ON COLUMN COUPON.CP_CONTENT IS '내용';
COMMENT ON COLUMN COUPON.CP_DATE IS '쿠폰생성일';

CREATE SEQUENCE SEQ_CPNO
NOCACHE;

--------------------------------------------------
------------------- FILE 관련	 -----------------
--------------------------------------------------
CREATE TABLE ATTACHMENT (
	ATTACHMENT_NO	NUMBER	PRIMARY KEY,
	BOARD_NO	NUMBER	NULL,
	FILE_NAME	VARCHAR2(1000)	NOT NULL,
	SYS_NAME	VARCHAR2(1000)	NOT NULL,
    FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO)
);
COMMENT ON COLUMN ATTACHMENT.ATTACHMENT_NO IS '파일번호';
COMMENT ON COLUMN ATTACHMENT.BOARD_NO IS '게시판글번호';
COMMENT ON COLUMN ATTACHMENT.FILE_NAME IS '원본파일명';
COMMENT ON COLUMN ATTACHMENT.SYS_NAME IS '시스템파일명';

CREATE SEQUENCE SEQ_FILENO
NOCACHE;

--------------------------------------------------
-------------------- 송장 관련	 -----------------
--------------------------------------------------
CREATE TABLE DELIVERY (
	O_NO	NUMBER	NOT NULL UNIQUE,
	DV_DELIVERY	VARCHAR2(20)	NULL,
	DV_INVOICE_NO	VARCHAR2(200)	NULL,
	DV_SHIPPING	VARCHAR2(200)	NULL,
	DV_SHIP_DATE	DATE DEFAULT SYSDATE ,
	DV_PARCEL	VARCHAR2(150)	NULL,
    FOREIGN KEY (O_NO) REFERENCES MEMORDER(O_NO)
);
COMMENT ON COLUMN DELIVERY.O_NO IS '주문번호';
COMMENT ON COLUMN DELIVERY.DV_DELIVERY IS '배송방법';
COMMENT ON COLUMN DELIVERY.DV_INVOICE_NO IS '송장번호';
COMMENT ON COLUMN DELIVERY.DV_SHIPPING IS '배송추적';
COMMENT ON COLUMN DELIVERY.DV_SHIP_DATE IS '발송일';
COMMENT ON COLUMN DELIVERY.DV_PARCEL IS '택배사';

CREATE SEQUENCE SEQ_DVNO
NOCACHE;

COMMIT;
